# Encoding: utf-8

# --
# Copyright (c) 2008-2021 Net-ng.
# All rights reserved.
#
# This software is licensed under the BSD License, as described in
# the file LICENSE.txt, which you should have received as part of
# this distribution.
# --

image: docker-registry.net-ng.com/nng/dind-ubuntu:7

tests:
  script:
    - pip3 install flake8
    - flake8 nagare
